# Generated by Django 2.2.2 on 2019-06-11 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='')),
                ('survived', models.BooleanField()),
                ('age', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sexo', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('ticket_class', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
